apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
        ports:
        - containerPort: 3000
