replicaCount: 1

frontend:
  repository: vdevopsvinod/coin-frontend
  tag: "v1"
  servicePort: 80

backend:
  repository: vdevopsvinod/coin-backend
  tag: "7"
  servicePort: 3000

redis:
  image: redis:alpine
  port: 6379

service:
  port: 80
